using System;
using System.Collections;
using System.Diagnostics;
using System.Reflection;
using HarmonyLib;
using Sandbox.Game.Entities;
using Sandbox.Game.Entities.Character;
using Sandbox.Game.GameSystems;
using Sandbox.Game.World;
using SpaceEngineersVR.OpenXR;
using VRage.Game.Entity;
using VRageMath;
using VRageRender;
using VRageRender.Messages;

namespace SpaceEngineersVR.Rendering
{
    /// <summary>
    /// A screen showing the ship (or the character on foot) from a chase camera behind and above it, while the player
    /// stays in first person; or the view from one of the ship's camera blocks (<see cref="ExternalViewSource"/> says which,
    /// and the actions wheel chooses). A third scene pass, drawn after the eyes through the same DrawGameScene the eyes use,
    /// into a small texture; on the desktop it is laid over the lower left of each eye's part of the window, in the headset
    /// it is an extra quad layer on the dash (see <see cref="XrSession.Screen"/>).
    /// </summary>
    /// <remarks>
    /// Why a pass from a different place can see its own view: the engine culls inside each DrawGameScene, from
    /// Environment.Matrices (ViewFrustumClippedD and CameraPosition; MyCullManager.InitFrame -> MyCullQueries.AddMainViewPass),
    /// not once per frame from the game's camera. Setting the matrices as <see cref="EnvMatrices.MakeEye"/> does for an
    /// eye - the view moved, CameraPosition left at the head - therefore culls, lights and draws from the chase camera.
    ///
    /// The pass is small (<see cref="TextureWidth"/> x <see cref="TextureHeight"/>) but the renderer sizes its screen
    /// resources (GBuffer, light tiles, auto-exposure) once, from m_resolution, so it gets a set of its own that is
    /// swapped in around the pass (<see cref="SwapIn"/>), together with m_resolution, ViewportResolution and
    /// FullResViewport. Everything else the pass would leave behind for the eyes' next frame is kept out of it: sun
    /// shadows (the cascades are cached between passes), spot light shadows (and their list), flares and group occlusion
    /// queries (the eyes would be culled by what the chase camera could not see: <c>MyActor.IsOccluded</c> is patched off for the
    /// pass), foliage and GPU particles (simulated and generated by each pass), and SSAO (its textures are screen sized).
    /// </remarks>
    internal static class ExternalView
    {
        public const int TextureWidth = 640, TextureHeight = 360;

        /// <summary>The chase camera's vertical field of view, degrees.</summary>
        private const float FieldOfViewDegrees = 60f;

        /// <summary>The widest and the narrowest vertical field of view a camera block's picture is drawn with, radians.</summary>
        private const float MinFieldOfView = 0.1f, MaxFieldOfView = 2.5f;

        /// <summary>A picture older than this (seconds) is no longer shown: nothing to chase, or the pass keeps failing.</summary>
        private const double FreshSeconds = 1.0;

        /// <summary>A camera snapshot older than this (seconds) is not used for a pass.</summary>
        private const double SnapshotSeconds = 0.5;

        /// <summary>Where the screen stands on the dash, from the head at rest: right, up, forward (negative z), metres.</summary>
        private static readonly Vector3 DashOffset = new Vector3(-0.20f, -0.30f, -0.60f);

        private static readonly Assembly Render11 = typeof(MyDX11Render).Assembly;

        /// <summary>
        /// Debug (<see cref="RenderDebug"/> ExternalView=1 / 0): forced on or off whatever the setting says. Null follows the setting.
        /// </summary>
        public static bool? Debug { get; set; }

        /// <summary>Everything the pass needs was found, and nothing has failed yet.</summary>
        private static volatile bool available;

        /// <summary>True while the pass is being drawn. Read by the culling workers (<see cref="SkipOcclusion"/>).</summary>
        private static volatile bool drawing;

        /// <summary>The screen is on: the setting or the debug switch, and the pass works.</summary>
        public static bool Wanted => available && On;

        /// <summary>The screen is switched on: RenderDebug's override if there is one, else the setting (whether or not the pass works).</summary>
        public static bool On => Debug ?? VRSettings.ExternalViewOn;

        /// <summary>The pass works (it is turned off for the rest of the run after a failure).</summary>
        public static bool Usable => available;

        // ---- reflection: the renderer's own members ----
        private static Type render, gbufferType, lightsType, eyeAdaptationType, managersType;
        private static FieldInfo resolution, fullResViewport, gbufferMain, gbufferSamples, gbufferQuality, gbufferHdr;
        private static PropertyInfo viewportResolution, debugOverrides;
        private static MethodInfo gbufferResize, gbufferRelease, lightsResize, lightsDispose;
        private static FieldInfo[] lightFields;
        private static FieldInfo autoExposure, rwTextures, shadowsManager, tempShadowLights;
        private static MethodInfo createRtv, disposeRtv, copyResourceToResource, occlusionRender;

        // ---- the camera, from the game thread ----
        private const int Capacity = 16;
        private static readonly object gate = new object();
        private static readonly MatrixD[] views = new MatrixD[Capacity];
        private static readonly MatrixD[] poses = new MatrixD[Capacity];
        private static readonly float[] fields = new float[Capacity];
        private static readonly long[] stamps = new long[Capacity];
        private static int next;
        private static int misses;
        private static bool captureFailureLogged;

        // ---- the picture and the screen resources, on the render thread ----
        private static object texture;
        private static long drawnAt;
        private static bool haveImage;
        private static object smallGBuffer;
        private static object[] smallLights;
        private static object smallExposure;
        private static bool screenSetBuilt, screenSetJustBuilt;
        private static bool placed;
        private static Matrix dash;
        private static XrSession.Screen? pending;

        /// <summary>The pass has drawn something lately, and the screen is on.</summary>
        public static bool Showing => Wanted && haveImage && Seconds(Stopwatch.GetTimestamp() - drawnAt) < FreshSeconds;

        private static double Seconds(long ticks) => (double)ticks / Stopwatch.Frequency;

        public static void Patch(Harmony harmony)
        {
            try
            {
                Resolve();
            }
            catch (Exception e)
            {
                Log.Error(e, "External view: the renderer's members were not found; the screen is off");
                return;
            }

            try
            {
                harmony.Patch(AccessTools.Method(typeof(MyRenderProxy), nameof(MyRenderProxy.SetCameraViewMatrix)),
                    postfix: new HarmonyMethod(typeof(ExternalView), nameof(Capture)));
                harmony.Patch(AccessTools.Method(typeof(VRage.Render.Scene.MyActor), nameof(VRage.Render.Scene.MyActor.IsOccluded)),
                    prefix: new HarmonyMethod(typeof(ExternalView), nameof(SkipOcclusion)));
                harmony.Patch(occlusionRender, prefix: new HarmonyMethod(typeof(ExternalView), nameof(SkipOcclusionQueries)));
                harmony.Patch(AccessTools.Method(render, "CreateScreenResources"),
                    postfix: new HarmonyMethod(typeof(ExternalView), nameof(ScreenResourcesChanged)));
                available = true;
                Log.Info("External view patched");
            }
            catch (Exception e)
            {
                Log.Error(e, "External view could not be hooked; the screen is off");
            }
        }

        private static void Resolve()
        {
            render = Render11.GetType("VRageRender.MyRender11", throwOnError: true);
            gbufferType = Render11.GetType("VRage.Render11.Resources.MyGBuffer", throwOnError: true);
            lightsType = Render11.GetType("VRage.Render11.LightingStage.MyLightsRendering", throwOnError: true);
            eyeAdaptationType = Render11.GetType("VRageRender.MyEyeAdaptation", throwOnError: true);
            managersType = Render11.GetType("VRage.Render11.Common.MyManagers", throwOnError: true);

            resolution = Field(render, "m_resolution");
            fullResViewport = Field(render, "FullResViewport");
            viewportResolution = AccessTools.Property(render, "ViewportResolution") ?? throw new MissingMemberException("MyRender11.ViewportResolution");
            debugOverrides = AccessTools.Property(render, "DebugOverrides") ?? throw new MissingMemberException("MyRender11.DebugOverrides");

            gbufferMain = Field(gbufferType, "Main");
            gbufferSamples = Field(gbufferType, "m_samplesCount");
            gbufferQuality = Field(gbufferType, "m_samplesQuality");
            gbufferHdr = Field(gbufferType, "m_hdrType");
            gbufferResize = AccessTools.Method(gbufferType, "Resize") ?? throw new MissingMemberException("MyGBuffer.Resize");
            gbufferRelease = AccessTools.Method(gbufferType, "Release") ?? throw new MissingMemberException("MyGBuffer.Release");

            lightFields = new[]
            {
                Field(lightsType, "m_tileIndices"), Field(lightsType, "m_tilesNum"), Field(lightsType, "m_tilesX"),
                Field(lightsType, "m_tilesY"), Field(lightsType, "m_isLightPreparedAfterResize"),
            };
            lightsResize = AccessTools.Method(lightsType, "Resize", new[] { typeof(int), typeof(int) }) ?? throw new MissingMemberException("MyLightsRendering.Resize");
            lightsDispose = AccessTools.Method(lightsType, "Dispose", Type.EmptyTypes) ?? throw new MissingMemberException("MyLightsRendering.Dispose");

            occlusionRender = AccessTools.Method(Render11.GetType("VRage.Render11.Culling.Occlusion.MyActorOcclusionRenderer", throwOnError: true), "Render")
                              ?? throw new MissingMemberException("MyActorOcclusionRenderer.Render");

            autoExposure = Field(eyeAdaptationType, "m_autoExposure");
            rwTextures = Field(managersType, "RwTextures");
            shadowsManager = Field(managersType, "Shadows");
            tempShadowLights = Field(shadowsManager.FieldType, "m_tempShadowLights");
            createRtv = AccessTools.Method(rwTextures.FieldType, "CreateRtv") ?? throw new MissingMemberException("MyRwTextureManager.CreateRtv");
            Type rtvTexture = Render11.GetType("VRage.Render11.Resources.IRtvTexture", throwOnError: true);
            disposeRtv = AccessTools.Method(rwTextures.FieldType, "DisposeTex", new[] { rtvTexture.MakeByRefType() }) ?? throw new MissingMemberException("MyRwTextureManager.DisposeTex(ref IRtvTexture)");
            Type resource = Render11.GetType("VRage.Render11.Resources.IResource", throwOnError: true);
            copyResourceToResource = AccessTools.Method(Render11.GetType("VRage.Render11.RenderContext.MyRenderContext", throwOnError: true),
                "CopyResource", new[] { resource, resource }) ?? throw new MissingMemberException("MyRenderContext.CopyResource(IResource, IResource)");
        }

        private static FieldInfo Field(Type type, string name) =>
            AccessTools.Field(type, name) ?? throw new MissingFieldException(type.Name, name);

        // ------------------------------------------------------------------------------------------------------
        // Game thread: where the chase camera is
        // ------------------------------------------------------------------------------------------------------

        /// <summary>
        /// Game thread, as the camera goes to the renderer: the chase camera for this frame, in the game camera's own
        /// space, keyed by the view matrix so that the renderer, which may be a message behind, pairs it with the ship
        /// as that frame drew it (the same way <see cref="Tracking.CameraHeadLink"/> pairs the head).
        /// </summary>
        private static void Capture(MatrixD viewMatrix)
        {
            if (!Wanted)
                return;
            try
            {
                if (!TryViewpoint(out MatrixD camera, out float field))
                    return;
                lock (gate)
                {
                    views[next] = viewMatrix;
                    poses[next] = camera * viewMatrix;
                    fields[next] = field;
                    stamps[next] = Stopwatch.GetTimestamp();
                    next = (next + 1) % Capacity;
                }
            }
            catch (Exception e)
            {
                if (!captureFailureLogged)
                {
                    captureFailureLogged = true;
                    Log.Error(e, "External view: could not place the chase camera");
                }
            }
        }

        /// <summary>
        /// Where the picture is taken from this frame: the chosen camera block's view (its world matrix and field of view,
        /// read only: the player's own view is never moved to it, and the block is never made the active camera), or the
        /// chase camera when that is the source, or when the chosen camera cannot be used now (<see cref="ExternalViewSource"/>
        /// says so once).
        /// </summary>
        private static bool TryViewpoint(out MatrixD camera, out float field)
        {
            field = MathHelper.ToRadians(FieldOfViewDegrees);
            if (ExternalViewSource.TryCameraView(out camera, out float cameraField))
            {
                field = MathHelper.Clamp(cameraField, MinFieldOfView, MaxFieldOfView);
                return true;
            }
            return TryChaseCamera(out camera);
        }

        /// <summary>
        /// The chase camera's world matrix: behind and above what the player controls, looking at it, horizon level
        /// (up is against natural gravity; in space, up is the ship's own).
        /// </summary>
        private static bool TryChaseCamera(out MatrixD camera)
        {
            camera = MatrixD.Identity;
            MySession session = MySession.Static;
            var controlled = session?.ControlledEntity;
            if (controlled == null || session.IsCameraUserControlledSpectator())
                return false;

            MatrixD frame;
            Vector3D center;
            double distance, height;
            MyEntity entity = controlled.Entity;
            if (entity is MyCharacter character)
            {
                frame = character.PositionComp.WorldMatrixRef;
                center = frame.Translation + frame.Up * 1.0;
                distance = 3.5;
                height = 1.0;
            }
            else
            {
                MyCubeGrid grid = (entity as MyCubeBlock)?.CubeGrid ?? entity?.GetTopMostParent() as MyCubeGrid;
                if (grid == null)
                    return false;
                frame = grid.PositionComp.WorldMatrixRef;
                BoundingSphereD volume = grid.PositionComp.WorldVolume;
                center = volume.Center;
                distance = MathHelper.Clamp(volume.Radius * 2.4 + 3.0, 6.0, 400.0);
                height = distance * 0.28;
            }

            Vector3 gravity = MyGravityProviderSystem.CalculateNaturalGravityInPoint(center);
            return Compose(frame, center, gravity, distance, height, out camera);
        }

        /// <summary>
        /// The chase camera for something at <paramref name="center"/> facing along <paramref name="frame"/>'s forward:
        /// <paramref name="distance"/> behind it along the horizon and <paramref name="height"/> above, looking at it,
        /// with the horizon level. Up is against <paramref name="gravity"/> where there is any, else the frame's own up.
        /// </summary>
        internal static bool Compose(in MatrixD frame, Vector3D center, Vector3 gravity, double distance, double height, out MatrixD camera)
        {
            camera = MatrixD.Identity;
            Vector3D up = frame.Up;
            if (gravity.LengthSquared() > 1e-4f)
                up = -Vector3D.Normalize((Vector3D)gravity);

            // Which way the ship faces along the horizon. Pointing nearly straight up or down, its forward says nothing
            // about that: use the way its top points then, as the world menu does for a head looking up or down.
            Vector3D forward = frame.Forward;
            Vector3D along = forward - up * forward.Dot(up);
            if (along.LengthSquared() < 0.04)
            {
                Vector3D top = frame.Up;
                along = top - up * top.Dot(up);
                if (forward.Dot(up) > 0.0)
                    along = -along;
            }
            if (along.LengthSquared() < 1e-6)
                along = Vector3D.Cross(up, frame.Right);
            if (along.LengthSquared() < 1e-6)
                return false;
            along.Normalize();

            Vector3D eye = center - along * distance + up * height;
            camera = MatrixD.CreateWorld(eye, Vector3D.Normalize(center - eye), up);
            return true;
        }

        // ------------------------------------------------------------------------------------------------------
        // Render thread: the pass
        // ------------------------------------------------------------------------------------------------------

        /// <summary>
        /// Draws the chase view into the picture (every other frame with <see cref="VRSettings.ExternalViewHalfRate"/>),
        /// after both eyes, and puts the head camera back. Never throws; on a failure the screen turns itself off.
        /// </summary>
        /// <param name="env">The renderer's environment matrices, as the head camera.</param>
        /// <param name="head">The head camera, to put back.</param>
        public static void Render(object env, in EnvMatrices.Snapshot head, int frame)
        {
            try
            {
                RenderPass(env, head, frame);
            }
            catch (Exception e)
            {
                available = false;
                haveImage = false;
                Log.Error(e, "External view: the chase pass could not start; the screen is off for the rest of the run");
            }
        }

        private static void RenderPass(object env, in EnvMatrices.Snapshot head, int frame)
        {
            if (!Wanted)
            {
                haveImage = false;
                placed = false;
                passTimed = false;
                return;
            }
            if (haveImage && VRSettings.ExternalViewHalfRate && (frame & 1) != 0)
                return;
            if (!TryGetPose(env, out Matrix eyeFromHead, out float field))
                return;
            long started = Stopwatch.GetTimestamp();
            bool first = !passTimed;

            MyRenderDebugOverrides overrides = (MyRenderDebugOverrides)debugOverrides.GetValue(null);
            bool shadows = overrides.Shadows, spotLights = overrides.SpotLights, flares = overrides.Flares,
                foliage = overrides.Foliage, particles = overrides.GPUParticles, ssao = overrides.SSAO;
            IList shadowLights = (IList)tempShadowLights.GetValue(shadowsManager.GetValue(null));
            var savedShadowLights = new ArrayList(shadowLights);
            Vector2I bigResolution = (Vector2I)resolution.GetValue(null);
            Vector2I bigViewport = (Vector2I)viewportResolution.GetValue(null);
            object bigFullRes = fullResViewport.GetValue(null);
            object bigGBuffer = gbufferMain.GetValue(null);
            object[] bigLights = new object[lightFields.Length];
            for (int i = 0; i < bigLights.Length; i++)
                bigLights[i] = lightFields[i].GetValue(null);
            object bigExposure = autoExposure.GetValue(null);

            try
            {
                EnsureTexture();
                EnsureScreenSet();

                resolution.SetValue(null, new Vector2I(TextureWidth, TextureHeight));
                viewportResolution.SetValue(null, new Vector2I(TextureWidth, TextureHeight));
                fullResViewport.SetValue(null, new MyViewport(TextureWidth, TextureHeight));
                gbufferMain.SetValue(null, smallGBuffer);
                for (int i = 0; i < smallLights.Length; i++)
                    lightFields[i].SetValue(null, smallLights[i]);
                autoExposure.SetValue(null, smallExposure);

                overrides.Shadows = overrides.SpotLights = overrides.Flares = overrides.Foliage = overrides.GPUParticles = overrides.SSAO = false;
                drawing = true;

                float v = (float)Math.Tan(field / 2.0);
                float h = v * TextureWidth / TextureHeight;
                EnvMatrices.MakeEye(env, eyeFromHead, new EnvMatrices.FovTangents { Left = -h, Right = h, Up = v, Down = -v });
                EyeRenderer.DrawSceneTo(texture);

                drawnAt = Stopwatch.GetTimestamp();
                haveImage = true;
                TimePass(first, drawnAt - started);
            }
            catch (Exception e)
            {
                available = false;
                haveImage = false;
                Log.Error(e, "External view: the chase pass failed; the screen is off for the rest of the run");
            }
            finally
            {
                drawing = false;
                overrides.Shadows = shadows;
                overrides.SpotLights = spotLights;
                overrides.Flares = flares;
                overrides.Foliage = foliage;
                overrides.GPUParticles = particles;
                overrides.SSAO = ssao;
                shadowLights.Clear();
                foreach (object light in savedShadowLights)
                    shadowLights.Add(light);

                autoExposure.SetValue(null, bigExposure);
                for (int i = 0; i < bigLights.Length; i++)
                    lightFields[i].SetValue(null, bigLights[i]);
                gbufferMain.SetValue(null, bigGBuffer);
                fullResViewport.SetValue(null, bigFullRes);
                viewportResolution.SetValue(null, bigViewport);
                resolution.SetValue(null, bigResolution);
                EnvMatrices.Restore(env, head);
            }
        }

        // The cost of the pass on the render thread (the time to record it, not the GPU's), for the log: what turning the
        // screen on costs the frame it first draws, and what it costs once running.
        private const int TimedPasses = 120;
        private static bool passTimed;
        private static int passCount;
        private static double passMillis, firstPassMillis;
        private static string timingWhy = "it was turned on";

        /// <summary>The next pass is timed for the log as a first one: the source was switched (<paramref name="why"/>).</summary>
        public static void Retime(string why)
        {
            timingWhy = why;
            passTimed = false;
        }

        /// <summary>Logs the first pass after the screen was turned on, and then the average of the next <see cref="TimedPasses"/>.</summary>
        private static void TimePass(bool first, long ticks)
        {
            double ms = Seconds(ticks) * 1000.0;
            if (first)
            {
                passTimed = true;
                passCount = 0;
                passMillis = 0.0;
                firstPassMillis = ms;
                Log.Info($"External view: the first pass after {timingWhy} took {ms:0.0} ms on the render thread" + (screenSetJustBuilt ? " (the pass's own screen resources were made then)" : " (its resources were already made)"));
                screenSetJustBuilt = false;
                timingWhy = "it was turned on";
                return;
            }
            if (passCount >= TimedPasses)
                return;
            passMillis += ms;
            if (++passCount == TimedPasses)
                Log.Info($"External view: the next {TimedPasses} passes took {passMillis / TimedPasses:0.0} ms each on the render thread (the first took {firstPassMillis:0.0} ms)");
        }

        /// <summary>The camera sent with the game camera this pass is relative to, as the eye-from-head matrix <see cref="EnvMatrices.MakeEye"/> takes, and its vertical field of view in radians.</summary>
        private static bool TryGetPose(object env, out Matrix eyeFromHead, out float field)
        {
            eyeFromHead = Matrix.Identity;
            field = MathHelper.ToRadians(FieldOfViewDegrees);
            MatrixD view = EnvMatrices.ViewD(env);
            long now = Stopwatch.GetTimestamp();
            lock (gate)
            {
                int newest = -1;
                for (int i = 1; i <= Capacity; i++)
                {
                    int index = (next - i + Capacity) % Capacity;
                    if (stamps[index] == 0 || Seconds(now - stamps[index]) > SnapshotSeconds)
                        continue;
                    if (newest < 0)
                        newest = index;
                    if (views[index] == view)
                    {
                        eyeFromHead = (Matrix)poses[index];
                        field = fields[index];
                        return true;
                    }
                }
                if (newest < 0)
                    return false;
                // The camera the renderer holds is not among the recent ones: the newest chase camera is a frame off at worst.
                eyeFromHead = (Matrix)poses[newest];
                field = fields[newest];
            }
            if ((++misses & (misses - 1)) == 0)
                Log.Warn($"External view: camera not found among the recent ones (miss {misses}); using the newest");
            return true;
        }

        /// <summary>The picture: made the first time, and again after the render size changes nothing about it (it has a size of its own).</summary>
        private static void EnsureTexture()
        {
            if (texture != null)
                return;
            texture = createRtv.Invoke(rwTextures.GetValue(null), new object[]
            {
                "VR external view", TextureWidth, TextureHeight, EyeRenderer.WindowFormat, 1, 0,
                SharpDX.Direct3D11.ResourceOptionFlags.None, SharpDX.Direct3D11.ResourceUsage.Default, 1, SharpDX.Direct3D11.CpuAccessFlags.None,
            });
            EyeRenderer.Clear(texture);
        }

        // ------------------------------------------------------------------------------------------------------
        // The pass's own screen-sized resources
        // ------------------------------------------------------------------------------------------------------

        /// <summary>
        /// A GBuffer, the light tiles and the auto-exposure pair at the picture's size, made with the renderer's own
        /// functions (MyGBuffer.Resize, MyLightsRendering.Resize) while the big ones are kept out of their way.
        /// The exposure starts from where the eyes' is, so the picture is not dark for the first second.
        /// </summary>
        private static void EnsureScreenSet()
        {
            if (screenSetBuilt)
                return;

            object big = gbufferMain.GetValue(null);
            object hdr = gbufferHdr.GetValue(null);
            object samples = gbufferSamples.GetValue(big);
            object quality = gbufferQuality.GetValue(big);
            object gbuffer = Activator.CreateInstance(gbufferType, nonPublic: true);
            gbufferResize.Invoke(gbuffer, new[] { TextureWidth, TextureHeight, samples, quality, hdr });

            object[] bigLights = new object[lightFields.Length];
            for (int i = 0; i < bigLights.Length; i++)
                bigLights[i] = lightFields[i].GetValue(null);
            object[] lights = new object[lightFields.Length];
            try
            {
                // Resize disposes what is there first: with nothing there, it builds the small set and leaves the big one alone.
                lightFields[0].SetValue(null, null);
                lightsResize.Invoke(null, new object[] { TextureWidth, TextureHeight });
                for (int i = 0; i < lights.Length; i++)
                    lights[i] = lightFields[i].GetValue(null);
            }
            finally
            {
                for (int i = 0; i < bigLights.Length; i++)
                    lightFields[i].SetValue(null, bigLights[i]);
            }

            Type rtvTexture = autoExposure.FieldType.GetElementType();
            Array exposure = Array.CreateInstance(rtvTexture, 2);
            object bigExposure = ((Array)autoExposure.GetValue(null)).GetValue(0);
            object rc = EyeRenderer.Context;
            for (int i = 0; i < 2; i++)
            {
                object created = createRtv.Invoke(rwTextures.GetValue(null), new object[]
                {
                    "AutoExposureExternal" + i, 1, 1, SharpDX.DXGI.Format.R32G32_Float, 1, 0,
                    SharpDX.Direct3D11.ResourceOptionFlags.None, SharpDX.Direct3D11.ResourceUsage.Default, 1, SharpDX.Direct3D11.CpuAccessFlags.None,
                });
                exposure.SetValue(created, i);
                copyResourceToResource.Invoke(rc, new[] { bigExposure, created });
            }

            smallGBuffer = gbuffer;
            smallLights = lights;
            smallExposure = exposure;
            screenSetBuilt = true;
            screenSetJustBuilt = true;
            Log.Info($"External view: screen resources made at {TextureWidth}x{TextureHeight}");
        }

        /// <summary>The renderer made its screen resources again (a new size, a new anti-aliasing mode): the small set is made again too, next time.</summary>
        private static void ScreenResourcesChanged()
        {
            if (!screenSetBuilt)
                return;
            screenSetBuilt = false;
            try
            {
                gbufferRelease.Invoke(smallGBuffer, null);

                object[] bigLights = new object[lightFields.Length];
                for (int i = 0; i < bigLights.Length; i++)
                    bigLights[i] = lightFields[i].GetValue(null);
                try
                {
                    for (int i = 0; i < smallLights.Length; i++)
                        lightFields[i].SetValue(null, smallLights[i]);
                    lightsDispose.Invoke(null, null);
                }
                finally
                {
                    for (int i = 0; i < bigLights.Length; i++)
                        lightFields[i].SetValue(null, bigLights[i]);
                }

                Array exposure = (Array)smallExposure;
                for (int i = 0; i < exposure.Length; i++)
                {
                    object[] args = { exposure.GetValue(i) };
                    disposeRtv.Invoke(rwTextures.GetValue(null), args);
                }
            }
            catch (Exception e)
            {
                Log.Error(e, "External view: freeing the screen resources failed");
            }
            smallGBuffer = null;
            smallLights = null;
            smallExposure = null;
        }

        /// <summary>
        /// MyActorOcclusionRenderer.Render issues the group occlusion queries for a cull query and stores their results in
        /// the actors, per view id - the main view's id, which the chase pass shares with the eyes. Skipped for the pass, so
        /// the eyes' queries and results are not overwritten with what the chase camera saw.
        /// </summary>
        private static bool SkipOcclusionQueries() => !drawing;

        /// <summary>
        /// The pass's culling must not take the eyes' occlusion results (what is hidden behind the cockpit from the head
        /// is not hidden from the chase camera). The eyes' pass keeps its own, written by their own queries.
        /// </summary>
        private static bool SkipOcclusion(ref bool __result)
        {
            if (!drawing)
                return true;
            __result = false;
            return false;
        }

        // ------------------------------------------------------------------------------------------------------
        // Showing the picture
        // ------------------------------------------------------------------------------------------------------

        /// <summary>
        /// The desktop: the picture over the lower left of each eye's part of the window (a quarter of its width), after
        /// the eyes were copied into it. With a headset the window shows the left eye, so it shows the picture too.
        /// </summary>
        public static void ShowInWindow(object window, Vector2I windowSize)
        {
            if (!Showing)
                return;
            for (int i = 0; i < 2; i++)
            {
                MyViewport area = EyeRenderer.Eyes[i].Window;
                if (area.Width <= 0f)
                    continue;
                float left = Math.Max(area.OffsetX, 0f), right = Math.Min(area.OffsetX + area.Width, windowSize.X);
                float top = Math.Max(area.OffsetY, 0f), bottom = Math.Min(area.OffsetY + area.Height, windowSize.Y);
                if (right - left < 16f || bottom - top < 16f)
                    continue;
                float width = (right - left) * 0.25f, height = width * TextureHeight / TextureWidth;
                float margin = (right - left) * 0.02f;
                EyeRenderer.CopyOpaque(window, texture, new MyViewport(left + margin, bottom - margin - height, width, height));
            }
        }

        /// <summary>
        /// The headset: copies the picture into the screen's swapchain and places the screen on the dash, to be submitted
        /// with this frame (<see cref="TakeLayer"/>). The screen is put where the head is the first time it is shown, and
        /// stays there in the tracking space, which the game keeps in the cockpit.
        /// </summary>
        /// <param name="head">The head in the tracking space.</param>
        public static void ShowInHeadset(in Matrix head)
        {
            pending = null;
            if (!Showing)
            {
                placed = false;
                return;
            }
            if (!XrSession.InFrame || !XrSession.ShouldRender)
                return;
            try
            {
                if (!placed)
                {
                    dash = Place(head);
                    placed = true;
                    Vector3 at = dash.Translation;
                    Log.Info($"External view: screen placed on the dash at ({at.X:0.00}, {at.Y:0.00}, {at.Z:0.00}) in the tracking space");
                }
                SharpDX.Direct3D11.Texture2D image = XrSession.AcquireScreenImage(TextureWidth, TextureHeight);
                try
                {
                    EyeRenderer.CopyToImage(texture, image);
                }
                finally
                {
                    XrSession.ReleaseScreenImage();
                }
                float width = VRSettings.ExternalViewSize;
                Quaternion rotation = Quaternion.CreateFromRotationMatrix(dash);
                Vector3 position = dash.Translation;
                pending = new XrSession.Screen
                {
                    Width = width,
                    Height = width * TextureHeight / TextureWidth,
                    Pose = new XrPosef
                    {
                        Orientation = new XrQuaternionf { X = rotation.X, Y = rotation.Y, Z = rotation.Z, W = rotation.W },
                        Position = new XrVector3f { X = position.X, Y = position.Y, Z = position.Z },
                    },
                };
            }
            catch (Exception e)
            {
                available = false;
                Log.Error(e, "External view: showing it in the headset failed; the screen is off for the rest of the run");
            }
        }

        /// <summary>The screen to submit with this headset frame, if there is one.</summary>
        public static XrSession.Screen? TakeLayer()
        {
            XrSession.Screen? layer = pending;
            pending = null;
            return layer;
        }

        /// <summary>
        /// The dash: <see cref="DashOffset"/> from the head along the horizon (the way it faces now), tilted to face
        /// the head. Panels in the tracking space face +z; <see cref="Matrix.CreateWorld"/> points -z along its forward.
        /// </summary>
        private static Matrix Place(in Matrix head)
        {
            Vector3 forward = head.Forward;
            Vector3 along = new Vector3(forward.X, 0f, forward.Z);
            if (along.LengthSquared() < 0.04f)
            {
                Vector3 up = head.Up;
                along = forward.Y < 0f ? new Vector3(up.X, 0f, up.Z) : new Vector3(-up.X, 0f, -up.Z);
            }
            if (along.LengthSquared() < 1e-6f)
                along = Vector3.Forward;
            along.Normalize();

            Matrix facing = Matrix.CreateWorld(Vector3.Zero, along, Vector3.Up);
            Vector3 centre = head.Translation + Vector3.TransformNormal(DashOffset, facing);
            return Matrix.CreateWorld(centre, Vector3.Normalize(centre - head.Translation), Vector3.Up);
        }
    }
}
